### ISSUE TITLE
[BUG]自动补充体力点不到小饼干

### ISSUE THREAD

**Issue by gsxgmpkt9020** [moulai/MaaAshEchoes#5]
![comic](https://github.com/user-attachments/assets/fecbc573-3a4c-4a6a-9caa-f7ac299c405e)

同时希望也能用上后备体力

**Comment by moulai** [comment]
目前不会自动使用食物（暂时也没计划加上吃体力药的功能，以避免误操作，白荆能扫荡，用体力药还是比较方便的）
